upstream_projection_parquet: "s3://oa-bolinas/snakemake/zoonomia_projection_dataset/results/projection/min0.20/all_species_with_sequence.parquet"
species_tsv: "../zoonomia_projection_dataset/config/species_zoonomia_447_family_dedup.tsv"

audit_sample_size: 8192
audit_sample_seed: 402

species_order_version: "zoonomia-rag-v1"
species_order:
  - "Microgale_talazaci"
  - "Loxodonta_africana"
  - "Tolypeutes_matacus"
  - "Bos_taurus"
  - "Equus_caballus"
  - "Mus_musculus"
  - "Microcebus_murinus"
  - "Homo_sapiens"

validation_size: 2048
validation_seed: 42
training_shuffle_seed: 42
training_n_shards: 32

hf_training_repo: "bolinas-dna/zoonomia-rag-v1-v1"

source_mendelian_harness:
  train: "https://huggingface.co/datasets/bolinas-dna/evals_mendelian_traits_harness_255/resolve/7b92f047f9a36f90e9ac47886afa2a99264ee35c/train.parquet"
  test: "https://huggingface.co/datasets/bolinas-dna/evals_mendelian_traits_harness_255/resolve/7b92f047f9a36f90e9ac47886afa2a99264ee35c/test.parquet"
upstream_species_twobit_prefix: "s3://oa-bolinas/snakemake/zoonomia_projection_dataset/results/projection/genomes"
hf_mendelian_repo: "bolinas-dna/evals_mendelian_traits_rag_harness_255_v1"
