default-storage-provider: s3
default-storage-prefix: s3://oa-bolinas/snakemake/vertebrate_projection_dataset/
cores: 2
use-conda: true
resources:
  mem_mb: 30000
  ucsc_downloads: 4
  final_large_scan: 1
  hf_uploads: 1
printshellcmds: true
rerun-triggers: mtime
