#import "../template.typ": paper-figure

= Introduction
<introduction>
Optimization of genomic language models (gLMs) has historically involved a lot of focus on specialized architectures.#footnote[For a broader overview, see #link("https://doi.org/10.1016/j.tig.2024.11.013")["Genomic language models: opportunities and challenges"]. Examples of specialized architectures include long-convolution or hybrid long-context models such as #link("https://arxiv.org/abs/2306.15794")[HyenaDNA] and #link("https://doi.org/10.1101/2025.02.18.638918")[Evo 2]\; U-Net-like models such as #link("https://doi.org/10.64898/2025.12.22.695963")[NTv3]\; bidirectional models such as #link("https://arxiv.org/abs/2306.15006")[DNABERT-2], #link("https://www.biorxiv.org/content/10.1101/2023.06.12.544594v3.full.pdf")[GENA-LM], #link("https://doi.org/10.1101/2025.08.27.672609")[PlantCAD2], and #link("https://arxiv.org/abs/2507.19229")[TrinityDNA]\; state-space or hybrid state-space models such as #link("https://arxiv.org/abs/2502.10807")[HybriDNA], #link("https://arxiv.org/abs/2403.03234")[Caduceus], and #link("https://doi.org/10.1101/2025.08.27.672609")[PlantCAD2]\; reverse-complement equivariance in #link("https://arxiv.org/abs/2403.03234")[Caduceus]\; learned adaptive segmentation that replaces fixed tokenization in #link("https://arxiv.org/abs/2602.10603")[dnaHNet] and #link("https://arxiv.org/abs/2601.03019")[DNACHUNKER]\; the hierarchical, multiscale Transformer used by #link("https://www.biorxiv.org/content/10.1101/2023.12.18.572218v3.full")[megaDNA]\; and early or less-established sparse-expert models such as #link("https://arxiv.org/abs/2505.17257")[JanusDNA], #link("https://arxiv.org/abs/2512.07113")[PlantBiMoE], and #link("https://arxiv.org/abs/2412.13716")[MxDNA].] We take a different approach: keep the architecture within the standard GPT family and focus on data curation and mixtures, training hyperparameters, and model scale. The experiments below test how far that simpler, standardized recipe can go.

== Why alignment-free gLMs?
<why-alignment-free-glms>
Many of the strongest genomic sequence models rely on whole-genome alignments, as in #link("https://doi.org/10.1101/2025.09.21.677619")[GPN-Star],#footnote[Exact details are not yet available, but #link("https://www.radicalnumerics.ai/blog/omnii-health-preview")[Omnii] also appears to benefit from alignment-derived information.] or functional-genomics measurements, as in #link("https://doi.org/10.1038/s41586-025-10014-0")[AlphaGenome]---resources concentrated in a small number of well-studied species because they are costly to produce and difficult to construct comprehensively. Unlabeled DNA sequence, by contrast, is available for a rapidly growing number of species. Alignment-free gLMs---also called single-sequence gLMs---can be trained directly on this growing collection of genomes and applied to evolutionary constraint prediction, sequence design, and transfer learning.

For humans and other well-studied species, single-sequence gLMs are still far from replacing alignment-based models or models supervised with functional-genomics data. Our near-term goal is to build useful models for species that lack high-quality whole-genome alignments and functional-genomics data. As a concrete example, we aim to enable accurate, cost-effective genome-wide mapping of evolutionary constraint for any mammalian species.#footnote[Zoonomia illustrates the gap between having an alignment and having a ready-to-use constraint track for each mammalian genome. Producing these tracks requires running per-base scoring in each target genome's coordinate system, which can require substantial intermediate storage and compute. The project's #link("https://zoonomiaproject.org/the-data/")[data page] links to a reference-free 241-way mammalian alignment, but the associated #link("https://cglgenomics.ucsc.edu/november-2020-nature-mammalian-and-avian-alignments/")[CGL resource page] offers a single score download explicitly labeled "Human PhyloP scores." The #link("https://cglgenomics.ucsc.edu/november-2023-nature-zoonomia-with-expanded-primates-alignment/")[expanded 447-way resource] publishes alignment files but no phyloP score downloads; UCSC's standard #link("https://hgdownload.soe.ucsc.edu/goldenPath/hg38/phyloP447way/")[447-way phyloP track] is likewise exposed only under human hg38. This is part of a broader gap: as of July 2026, UCSC's standard #link("https://hgdownload.soe.ucsc.edu/goldenPath/")[goldenPath] download tree contained phyloP tracks for only 20 species, nine of them mammals.] Longer term, sequence-only models may learn from sequence in ways that complement alignments, conservation scores, and functional-genomics models even in data-rich species (#link("https://github.com/Open-Athena/marin-dna/issues/396")[research question \#396]).

== Why data curation?
<why-data-curation>
Many early gLMs were trained on the human genome alone, with little to no filtering. Subsequent work made it clear that two factors were key drivers of model performance: including multiple species, and enriching for functional regions rather than sampling uniformly from the majority-neutral background of mammalian genomes.#footnote[See #link("https://doi.org/10.1016/j.tig.2024.11.013")[#emph[Genomic language models: opportunities and challenges]], #link("https://doi.org/10.1073/pnas.2311219120")[GPN], #link("https://doi.org/10.1073/pnas.2421738122")[PlantCaduceus], #link("https://doi.org/10.1101/2025.08.27.672609")[PlantCAD2], #link("https://www.biorxiv.org/content/10.1101/2025.09.19.677475v1")[Shorkie], #link("https://doi.org/10.1038/s41587-024-02511-w")[GPN-MSA], #link("https://doi.org/10.1186/s13059-024-03221-x")[Species-aware DNA language models], #link("https://doi.org/10.1038/s41588-025-02347-3")[nucleotide-dependency analysis], #link("https://doi.org/10.1038/s41586-026-10176-5")[Evo 2], and #link("https://doi.org/10.64898/2026.02.05.703637")[ARSENAL].]

In this work, we follow up on two findings from #link("https://doi.org/10.1101/2025.02.11.637758")[TraitGym]. First, 152M-parameter GPN-Promoter, trained only on animal promoters, performed comparably to Evo 2 40B on human promoter variants. Second, Evo 2 improved substantially with scale overall but still struggled on distal variants. Enhancers were the only region type not actively curated into its training data and were sparse among the intergenic regions it saw.

MarinDNA therefore treats dataset construction as a primary modeling lever: which species and evolutionary timescales to include (#link("https://github.com/Open-Athena/marin-dna/issues/394")[research question \#394]), which functional regions to sample and how to identify them (#link("https://github.com/Open-Athena/marin-dna/issues/395")[research question \#395]), how to weigh them, and when during training to introduce them.

We began with annotation-derived datasets for coding, upstream, and downstream sequences.#footnote["Downstream" denotes the 256 bp immediately downstream of each annotated CDS end, rather than annotated 3′ UTR intervals. In #link("https://github.com/Open-Athena/marin-dna/issues/53")[experiment \#53], this distance-based definition produced better 3′ UTR VEP performance than the annotation-derived baseline.] Standard genome annotations make these regions relatively easy to identify and extract consistently across many species.

Later, we added ncRNA#footnote[Most species had ncRNA annotations, but in #link("https://github.com/Open-Athena/marin-dna/issues/43")[experiment \#43], an annotation-derived ncRNA specialist showed little improvement on ncRNA variants. This motivated the later use of human annotations projected through whole-genome alignments.] and enhancers#footnote["Enhancer" is shorthand for the ENCODE V4 non-promoter cCRE set. It includes enhancer-like signatures (dELS and pELS), but also classes such as CA, CA-CTCF, CA-TF, CA-H3K4me3, and TF.] built by alignment projection. Because comparable annotations were not directly available across the target species, we projected human annotations through whole-genome alignments. The broader idea of using whole-genome alignments to expand reference-species enhancer data across species has also appeared recently in chromatin-accessibility prediction and enhancer-generation work.#footnote[#link("https://www.biorxiv.org/content/10.64898/2026.04.07.717039v2")[STEAM] augments mouse chromatin-accessibility training data with syntenic orthologs from 240 other mammalian genomes, while #link("https://www.biorxiv.org/content/10.64898/2026.04.13.718170v1")[EnhancAR] trains an autoregressive generator on families of human enhancers and their homologs.]

#paper-figure(
  "figures/data_provenance_training_datasets.svg",
  id: "fig-training-datasets",
  alt: "Token counts for annotation-derived CDS, upstream, and downstream datasets and alignment-projected enhancer and ncRNA datasets",
  caption: [*Training-dataset provenance and scale.*],
)
== Why GPT-style architecture?
<why-gpt-style-architecture>
By GPT-style, we mean the deliberately simple approach of treating DNA as text and training a stock causal, autoregressive, decoder-only language model on it. In these experiments, that architecture is literally Qwen3 rather than a genomics-specific design. This approach is not new; a substantial line of prior gLM work has used causal language modeling with GPT- or Llama-like architectures.#footnote[GPT-style or otherwise causal genomic models include #link("https://pmc.ncbi.nlm.nih.gov/articles/PMC9709791/")[GenSLM], #link("https://arxiv.org/abs/2307.05628")[DNAGPT], #link("https://doi.org/10.1101/2024.11.11.623015")[LOL-EVE], #link("https://arxiv.org/abs/2501.02045")[METAGENE-1], #link("https://arxiv.org/abs/2502.07272")[GENERATOR], #link("https://doi.org/10.64898/2026.01.27.702015")[GENERATOR-v2], #link("https://arxiv.org/abs/2503.16565")[Gene42], and #link("https://doi.org/10.64898/2026.05.22.727119")[Carbon]. The closest human-DNA precedents are Carbon, GENERATOR, Gene42, DNAGPT, and the promoter-focused LOL-EVE; several of the others are important causal gLM examples but are less directly relevant to human VEP.] What is new here is the quality target. Even recent models in this family, such as Carbon, generally aim for non-inferiority to smaller Evo 2 checkpoints and still underperform Evo 2 40B on the broad zero-shot VEP setting we care about.#footnote[The #link("https://huggingface.co/HuggingFaceBio/Carbon-3B")[Carbon-3B model card] describes Carbon-3B as a 3B-parameter decoder-only autoregressive genomic model implemented as a stock `LlamaForCausalLM`, with 6-mer DNA tokenization, long-context support, and a two-stage training schedule that switches from a standard cross-entropy objective to a factorized nucleotide supervision loss, bridging its coarse 6-mer tokenization with single-nucleotide resolution. Its public zero-shot table compares to Evo 2 7B, not Evo 2 40B: Carbon-3B is slightly ahead on BRCA2 and ClinVar noncoding, but behind on ClinVar coding and TraitGym Mendelian.] If the quality gap can be closed, GPT-style models have obvious advantages for deployment. They run through familiar training and inference stacks, move cleanly across hardware, and avoid model-specific kernels or bespoke architecture code, which matters a lot for cost, flexibility, and usability.

MarinDNA's first experiment compared three training objectives on promoter sequences: causal language modeling, masked language modeling, and masked diffusion (#link("https://github.com/Open-Athena/marin-dna/issues/3")[experiment \#3]). Causal language modeling looked most promising in the initial training steps. This was not a definitive matched-compute comparison of objectives, but it provided enough direction-setting evidence to pursue a simple causal architecture. That choice also need not permanently constrain the model to left-to-right representations: decoder-only language models can be adapted into bidirectional encoders with further training (#link("https://github.com/Open-Athena/marin-dna/issues/393")[research question \#393]).

Our initial goal was to model individual functional elements of the genome---such as an exon or an enhancer---well. We therefore deliberately used a short 255-bp context: it was sufficient for the functional-element tasks we tested and made training and evaluation much faster. Centering each example on an individual functional element also made the training data easier to construct, filter, audit, and interpret. How best to extend context---either through additional long-context next-token pretraining or during downstream-task fine-tuning---remains future work (#link("https://github.com/Open-Athena/marin-dna/issues/392")[research question \#392]).

== Why VEP evaluation?
<why-vep-evaluation>
Variant effect prediction (VEP) is one of the most important applications of gLMs. A useful VEP model can help scale clinical interpretation for rare disease, hereditary cancer, and variants of uncertain significance.#footnote[Examples include zero-shot or disease-focused variant interpretation results in #link("https://doi.org/10.1101/2025.02.18.638918")[Evo 2], #link("https://doi.org/10.1101/2025.09.21.677619")[GPN-Star], #link("https://doi.org/10.64898/2026.05.22.727119")[Carbon], and #link("https://arxiv.org/abs/2507.21706")[EnTao-GPM].] It can also help connect genetic association signals to disease mechanisms, target selection, and causal-variant prioritization in GWAS fine-mapping.#footnote[Examples include fine-mapped GWAS and broader human-genetics results in #link("https://doi.org/10.1101/2025.09.21.677619")[GPN-Star], regulatory variant-effect prediction in #link("https://doi.org/10.1101/2025.06.25.661532")[AlphaGenome] and #link("https://www.biorxiv.org/content/10.1101/2024.12.25.630221v2")[ChromBPNet], and the broader observation that human genetic evidence can support target-disease hypotheses in drug discovery in #link("https://doi.org/10.1038/ng.3314")[Nelson et al.].] The same kind of evidence is relevant to clinical trial design when genetics can inform patient stratification, enrollment criteria, or mechanism-based cohort definition. Together, these are commonly used levers for improving the efficiency of pharmaceutical development, and it is uncommon for other gLM evaluations to have such a direct connection to commercially relevant research tasks. VEP is also one of the few evaluations backed by decades of costly clinical genetics curation, with resources such as ClinVar and OMIM providing a level of human variant evidence that has no real analogue in other species.#footnote[#link("https://www.ncbi.nlm.nih.gov/clinvar/intro/")[ClinVar] archives submitted reports relating human genomic variation to disease, cancer, drug response, and supporting evidence; #link("https://doi.org/10.1093/nar/gku1205")[OMIM] is a curated catalog of human genes, genetic disorders, and gene-phenotype relationships. Nothing comparable exists for any other species: this depth reflects decades of clinical genetics effort directed specifically at human disease, an investment that has simply not been made for non-human genomes.] That combination makes it a substantive test of whether a gLM has learned sequence constraints that actually matter for human biology. If a model has learned useful sequence-level constraints from DNA alone, it should help rank variants in places where direct experimental evidence is weak or nonexistent.

This creates a deliberate mismatch between evaluation and intended use: although we expect single-sequence gLMs to be especially valuable for non-model organisms in the near term, we evaluate them in humans because comparable variant-effect data are not yet available across species. Human VEP is therefore the most rigorous available test of learned functional constraint, but it does not by itself establish transfer to other organisms; evaluating that transfer will require broader population-genetic or experimental datasets.

In this work, we focus on predicting deleteriousness, pathogenicity, or, more generally, functional constraint. This task is the one most directly connected to the language-modeling training objective and is therefore easy to evaluate with zero-shot or linear-probing protocols. We leave the prediction of changes in gene expression---the main application of sequence-to-function models---to follow-up work, as it requires more complex fine-tuning protocols and much larger context sizes.#footnote[One promising intermediate sequence-to-function target is chromatin accessibility. #link("https://doi.org/10.64898/2026.02.05.703637")[ARSENAL] showed that embeddings from a short-context regulatory gLM improved supervised chromatin-accessibility prediction over strong ab initio baselines across multiple cell types, while also improving regulatory-variant scoring.]

We use two complementary sources of evidence: clinically curated Mendelian variants#footnote[Our Mendelian benchmark is inspired by the published #link("https://doi.org/10.1101/2025.02.11.637758")[TraitGym] benchmark. Relative to TraitGym, we broadened the gnomAD control set by lowering the minimum allele frequency from 5% to 0.1%; we refer to variants above this threshold as non-rare. The larger control pool allowed us to match potential confounders within each consequence class---including TSS distance and, for splicing variants, exon distance---so that these features are largely non-predictive of the label. We also expanded the benchmark to include missense and splicing variants, incorporated additional sources of pathogenic variants, and created chromosome-disjoint splits for development and final testing. See the #link("https://huggingface.co/datasets/bolinas-dna/evals_mendelian_traits/tree/4aed58e50c5dea0b878a665007af2ef9e5108e9f")[pinned dataset card] for the full construction and matching diagnostics.] and saturation genome-editing (SGE) measurements. The Mendelian benchmark compares pathogenic and putatively benign variants across broad coding and non-coding consequence types. The SGE benchmark uses experimentally measured variant effects from a few genes in MaveDB, currently covering missense and splicing variants.

#paper-figure(
  "figures/eval_datasets.svg",
  id: "fig-evaluation-datasets",
  alt: "Clinical Mendelian and experimental SGE benchmarks, including labels and subset counts.",
  caption: [*Variant effect prediction benchmarks.*],
)
We evaluate each frozen gLM with two readouts: a zero-shot sequence log-likelihood ratio and a linear probe trained on paired reference/alternate embeddings. The zero-shot score tests whether the model's learned sequence likelihood reflects functional constraint: deleterious alternate alleles should incur larger likelihood penalties relative to the reference allele. The probe instead asks what variant-relevant information is encoded in the model's learned representation, including information that may not be directly reflected in its sequence likelihoods.

#paper-figure(
  "figures/eval_apparatus.svg",
  id: "fig-evaluation-readouts",
  alt: "Reference and alternate sequences scored using likelihoods or frozen-model embeddings.",
  caption: [*Variant effect prediction scoring approaches.*],
)
== Why compare with Evo 2 40B?
<why-compare-with-evo-2-40b>
Evo 2 40B remains the strongest broadly evaluated baseline among single-sequence DNA models. Despite substantial subsequent work on gLMs, we are not aware of a model in this setting that has clearly surpassed it across diverse genomic regions; many newer models do not attempt a direct comparison with Evo 2 40B. The other reason Evo 2 40B matters is its training budget. Its reported 2.25e24 training FLOPs are unrivaled among gLMs, corresponding to roughly \$2.5M of H100 time.#footnote[This estimate uses the #link("https://doi.org/10.1101/2025.02.18.638918")[Evo 2] reported training compute of 2.25e24 FLOPs, 50% H100 model FLOP utilization following the costing convention in #link("https://arxiv.org/abs/2401.00448")[Beyond Chinchilla], 989 TFLOP/s BF16 peak throughput for an H100 SXM, and \$2 per H100-hour from #link("https://arxiv.org/abs/2512.13961")[OLMo 3]. The resulting accelerator requirement is about 1.26M H100-hours.] That budget is unusual in biology and comparable to major open-weight LLM training runs from recent model generations,#footnote[Other over/under examples give the same intuition. The #link("https://huggingface.co/allenai/OLMo-2-0325-32B")[AI2 OLMo 2 32B model card] places Evo 2 40B above Gemma 2 27B, OLMo 2 32B, and Llama 3.1 8B. A dense-accounting estimate from the #link("https://github.com/meta-llama/llama-models/blob/main/models/llama3_1/MODEL_CARD.md")[Llama 3.1 model card] places it well below Llama 3.1 70B.] e.g.~just above Qwen2.5-14B and below Qwen2.5-32B, and roughly between DeepSeek-V2 and DeepSeek-V3. Evo 2 40B is therefore the right baseline for asking whether a much simpler single-sequence gLM can be competitive.
