= Introduction
<introduction>
Genomic language models (gLMs) learn statistical constraints directly from DNA sequence and can support variant-effect prediction, sequence design, and transfer learning @benegas2025review. Early sequence-only models showed that such constraints can predict the effects of genome-wide variants without task-specific labels @benegas2023gpn. More recent work has expanded model scale, context length, biological coverage, and architectural specialization, but it remains unclear how much of the resulting performance depends on specialized architectures rather than the data and optimization recipe.

The distinction matters because the strongest genomic predictors often use information that is unavailable outside a small number of well-studied species. GPN-Star explicitly models whole-genome alignments and phylogeny @ye2025gpnstar, whereas AlphaGenome is supervised on thousands of human and mouse functional-genomics tracks @avsec2026alphagenome. Sequence-only models require neither input at inference time and can therefore be applied wherever an assembled genome is available. They do not yet replace alignment-based or functional-genomics-supervised models in humans, but they may provide a practical route to genome-wide constraint prediction in species that lack those resources. Human evaluation is consequently a stringent proxy for this broader goal, not direct evidence of cross-species transfer.

We treat training-data construction as a primary modeling variable. TraitGym found that a 152M-parameter promoter specialist was competitive with Evo 2 40B on promoter variants, while Evo 2 scaling produced smaller gains on distal regulatory variants than on several other consequence classes @benegas2025traitgym. Those observations motivate explicit control over functional-region sampling rather than uniform sampling from mostly neutral genomic background. MarinDNA begins with coding, upstream, and downstream regions available from standard gene annotations, then adds non-coding RNA and candidate cis-regulatory elements by projecting human annotations across species. The experiments vary which regions are present, their mixture weights, and the stage of training at which they are introduced.

To isolate those choices, we use a conventional decoder-only Transformer rather than a genomics-specific sequence operator. The model is a nucleotide-level Qwen3 causal language model with a 255-base context, chosen to model individual functional elements while keeping training and variant scoring inexpensive. An initial objective comparison favored causal language modeling for subsequent development, but was not a definitive matched-compute comparison. Long-range regulatory modeling and bidirectional adaptation remain outside the scope of this study.

We evaluate frozen checkpoints on clinically curated Mendelian variants and saturation-genome-editing measurements. Each model is assessed through two complementary readouts: a zero-shot reference-versus-alternate sequence log-likelihood ratio and a chromosome-disjoint linear probe on paired allele embeddings. The likelihood score tests whether the training objective itself ranks deleterious alleles; the probe tests whether variant-relevant information is present in the learned representation even when it is not exposed by sequence likelihood. These evaluations measure human functional constraint and pathogenicity, not gene-expression changes or organism-level fitness.

Evo 2 40B is the principal sequence-only baseline because it is broadly evaluated across genomic regions and was trained at a substantially larger scale: 40B parameters, approximately 9.3T DNA tokens, and 2.25e24 reported training FLOPs @brixi2026evo2. Against that baseline, we ask whether a simpler and much smaller model can be made competitive through data curation and transferable optimization. We report three connected findings: optimizer settings calibrated at small scale transfer across model size, token horizon, and batch size; validation loss follows a predictable parameter-scaling trend but zero-shot missense performance does not improve monotonically; and a staged five-region training mixture yields a 1B-parameter model that is competitive with Evo 2 40B on the frozen Mendelian benchmark while requiring far less training compute and delivering higher as-deployed inference throughput.
