seed_graph:
  samples: ["100000"]
  variants:
    k9_s128_f8_m2: &seed_graph_variant
      kmer_length: 9
      selected_seeds_per_sequence: 128
      max_seed_frequency: 8
      min_shared_seeds: 2
      hash_seed: 521
      timeout: 20m
    k13_s128_f8_m2:
      <<: *seed_graph_variant
      kmer_length: 13
    k13_s128_f32_m2:
      <<: *seed_graph_variant
      kmer_length: 13
      max_seed_frequency: 32
    k15_s128_f8_m1:
      <<: *seed_graph_variant
      kmer_length: 15
      min_shared_seeds: 1
    k17_s148_f8_m1:
      <<: *seed_graph_variant
      kmer_length: 17
      selected_seeds_per_sequence: 148
      min_shared_seeds: 1
