"""Trace issue #417 inspection rows to backend-native projection fragments.

This one-off audit consumes the deterministic manual-inspection sample emitted by
the full pipeline.  HAL rows are checked against the preserved raw
``halLiftover`` BED, while MultiZ rows are regenerated by streaming the staged
chromosome MAF.  The resulting JSON is compact evidence for the human review;
it does not mark that review complete.
"""

from __future__ import annotations

import argparse
import json
from pathlib import Path
from typing import Any

import polars as pl

from marin_dna.pipelines.projection.hal import parse_halliftover_bed
from marin_dna.pipelines.projection.resize import resize_to_length
from marin_dna.pipelines.vertebrate_projection_dataset.contract import (
    apply_projection_contract,
)
from marin_dna.pipelines.vertebrate_projection_dataset.maf import (
    FRAGMENT_SCHEMA,
    iter_projected_anchor_fragments,
)


TARGET_LENGTH = 255
PRE_RESIZE_MIN_LENGTH = 128
PRE_RESIZE_MAX_LENGTH = 512
BACKENDS = ("zoonomia_cactus", "ucsc_multiz100way")


def _as_int(value: object) -> int:
    assert isinstance(value, int | str) and not isinstance(value, bool)
    return int(value)


def _assert_nonoverlapping(intervals: list[tuple[int, int]]) -> None:
    ordered = sorted(intervals)
    assert all(end > start >= 0 for start, end in ordered)
    assert all(left[1] <= right[0] for left, right in zip(ordered, ordered[1:]))


def _selected_rows(
    sample: pl.DataFrame, backend: str, rows_per_backend: int
) -> list[dict[str, Any]]:
    assert backend in BACKENDS
    selected = (
        sample.filter(pl.col("alignment_source") == backend)
        .sort(
            "fragment_count",
            "query_name",
            "alignment_name",
            descending=[True, False, False],
        )
        .head(rows_per_backend)
    )
    assert selected.height == rows_per_backend, (
        f"inspection sample has {selected.height} {backend} rows; "
        f"expected {rows_per_backend}"
    )
    return selected.to_dicts()


def _assert_contract_row(observed: dict[str, Any], expected: dict[str, Any]) -> None:
    for column in [
        "query_name",
        "source_chrom",
        "source_start",
        "source_end",
        "species",
        "alignment_name",
        "alignment_source",
        "t_chrom",
        "t_start",
        "t_end",
        "t_strand",
        "t_src_size",
        "fragment_count",
        "aligned_bases",
    ]:
        assert observed[column] == expected[column], (
            f"{expected['query_name']} / {expected['species']}: {column} "
            f"differs ({observed[column]!r} != {expected[column]!r})"
        )


def _trace_hal(results: Path, row: dict[str, Any]) -> dict[str, Any]:
    alignment_name = str(row["alignment_name"])
    raw_path = results / "hal" / "raw" / f"{alignment_name}.bed"
    assert raw_path.is_file(), f"missing raw halLiftover BED: {raw_path}"
    raw = parse_halliftover_bed(raw_path, alignment_name).filter(
        pl.col("query_name") == row["query_name"]
    )
    assert raw.height > 0, (
        f"raw HAL BED has no row for {row['query_name']} / {alignment_name}"
    )
    assert raw["t_chrom"].n_unique() == 1
    assert raw["t_strand"].n_unique() == 1
    assert raw["t_chrom"][0] == row["t_chrom"]
    assert raw["t_strand"][0] == row["t_strand"]

    intervals = [
        (_as_int(start), _as_int(end))
        for start, end in raw.select("t_start", "t_end").iter_rows()
    ]
    _assert_nonoverlapping(intervals)
    pre_resize_start = min(start for start, _ in intervals)
    pre_resize_end = max(end for _, end in intervals)
    pre_resize_length = pre_resize_end - pre_resize_start
    assert PRE_RESIZE_MIN_LENGTH <= pre_resize_length <= PRE_RESIZE_MAX_LENGTH
    target_start, target_end = resize_to_length(
        pre_resize_start,
        pre_resize_end,
        TARGET_LENGTH,
        _as_int(row["t_src_size"]),
    )
    assert (target_start, target_end) == (
        _as_int(row["t_start"]),
        _as_int(row["t_end"]),
    )
    aligned_bases = sum(end - start for start, end in intervals)
    assert raw.height == _as_int(row["fragment_count"])
    assert aligned_bases == _as_int(row["aligned_bases"])

    return {
        "query_name": row["query_name"],
        "species": row["species"],
        "alignment_name": alignment_name,
        "raw_path": str(raw_path),
        "raw_path_bytes": raw_path.stat().st_size,
        "raw_fragments": [
            {
                "t_chrom": raw_row["t_chrom"],
                "t_start": raw_row["t_start"],
                "t_end": raw_row["t_end"],
                "t_strand": raw_row["t_strand"],
            }
            for raw_row in raw.sort("t_start", "t_end").to_dicts()
        ],
        "pre_resize_interval": [pre_resize_start, pre_resize_end],
        "accepted_interval": [target_start, target_end],
        "aligned_bases": aligned_bases,
        "status": "matches preserved raw halLiftover BED",
    }


def _trace_multiz(
    results: Path,
    multiz_stage: Path,
    manifest: pl.DataFrame,
    row: dict[str, Any],
) -> dict[str, Any]:
    source_chrom = str(row["source_chrom"])
    maf_path = multiz_stage / "maf" / f"{source_chrom}.maf.gz"
    assert maf_path.is_file(), f"missing staged raw MAF: {maf_path}"
    anchor = pl.DataFrame(
        [
            {
                "query_name": row["query_name"],
                "source_chrom": source_chrom,
                "source_start": row["source_start"],
                "source_end": row["source_end"],
                "region_label": row["region_label"],
            }
        ]
    )
    alignment_name = str(row["alignment_name"])
    fragments = [
        fragment
        for fragment in iter_projected_anchor_fragments(
            maf_path,
            anchor,
            manifest,
        )
        if fragment["alignment_name"] == alignment_name
    ]
    assert fragments, (
        f"raw MAF has no projected fragment for {row['query_name']} / {alignment_name}"
    )
    frame = pl.DataFrame(fragments, schema=FRAGMENT_SCHEMA)
    result = apply_projection_contract(
        frame,
        target_length=TARGET_LENGTH,
        pre_resize_min_length=PRE_RESIZE_MIN_LENGTH,
        pre_resize_max_length=PRE_RESIZE_MAX_LENGTH,
    )
    assert result.rejected.is_empty(), (
        f"raw MAF replay rejected {row['query_name']} / {alignment_name}: "
        f"{result.rejected.to_dicts()}"
    )
    assert result.accepted.height == 1
    observed = result.accepted.row(0, named=True)
    _assert_contract_row(observed, row)

    return {
        "query_name": row["query_name"],
        "species": row["species"],
        "alignment_name": alignment_name,
        "raw_path": str(maf_path),
        "raw_path_bytes": maf_path.stat().st_size,
        "raw_fragments": [
            {
                "mapping_id": fragment["mapping_id"],
                "source_fragment_start": fragment["source_fragment_start"],
                "source_fragment_end": fragment["source_fragment_end"],
                "t_chrom": fragment["t_chrom"],
                "t_start": fragment["t_start"],
                "t_end": fragment["t_end"],
                "t_strand": fragment["t_strand"],
                "aligned_bases": fragment["aligned_bases"],
            }
            for fragment in sorted(
                fragments,
                key=lambda candidate: (
                    str(candidate["mapping_id"]),
                    str(candidate["fragment_id"]),
                ),
            )
        ],
        "accepted_interval": [observed["t_start"], observed["t_end"]],
        "aligned_bases": observed["aligned_bases"],
        "status": "matches fresh staged raw-MAF replay",
    }


def trace_samples(
    results: Path,
    multiz_stage: Path,
    *,
    rows_per_backend: int,
    expected_pipeline_commit: str,
) -> dict[str, Any]:
    assert results.is_dir(), f"missing results directory: {results}"
    assert multiz_stage.is_dir(), f"missing MultiZ stage: {multiz_stage}"
    assert rows_per_backend > 0
    assert len(expected_pipeline_commit) == 40
    sample = pl.read_csv(
        results / "qc" / "manual_inspection_sample.tsv", separator="\t"
    )
    manifest = pl.read_csv(results / "metadata" / "species_active.tsv", separator="\t")
    assert manifest["selected"].all()

    hal_rows = _selected_rows(sample, "zoonomia_cactus", rows_per_backend)
    multiz_rows = _selected_rows(sample, "ucsc_multiz100way", rows_per_backend)
    return {
        "results": str(results.resolve()),
        "expected_pipeline_commit": expected_pipeline_commit,
        "coordinate_system": "0-based half-open",
        "rows_per_backend": rows_per_backend,
        "hal": [_trace_hal(results, row) for row in hal_rows],
        "multiz": [
            _trace_multiz(results, multiz_stage, manifest, row) for row in multiz_rows
        ],
        "human_review": "pending",
        "status": "backend-native fragment traces passed",
    }


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("results", type=Path)
    parser.add_argument("multiz_stage", type=Path)
    parser.add_argument("--rows-per-backend", type=int, default=1)
    parser.add_argument("--expected-pipeline-commit", required=True)
    parser.add_argument("--output", type=Path, required=True)
    args = parser.parse_args()
    summary = trace_samples(
        args.results,
        args.multiz_stage,
        rows_per_backend=args.rows_per_backend,
        expected_pipeline_commit=args.expected_pipeline_commit,
    )
    rendered = json.dumps(summary, indent=2, sort_keys=True) + "\n"
    args.output.parent.mkdir(parents=True, exist_ok=True)
    args.output.write_text(rendered)
    print(rendered, end="")


if __name__ == "__main__":
    main()
