default-storage-provider: s3
default-storage-prefix: s3://oa-bolinas/snakemake/analysis/linclust_conservation/
cores: 2
use-conda: true
printshellcmds: true
resources:
  mem_mb: 7000
  staging_jobs: 1
  sampling_jobs: 1
